import { test, expect, login } from "./fixtures";
import sharp from "sharp";

test("GIF selection is saved, used by generation and gated by independent moderator approval", async ({page,accounts}) => {
  const owner=await accounts.create();
  const voter=await accounts.create();
  const moderator=await accounts.create();
  await login(page,owner);
  await page.goto("/challenges/new");
  const pngs=await Promise.all(Array.from({length:12},(_,i)=>sharp({create:{width:32,height:32,channels:3,background:{r:i*20,g:50,b:100}}}).png().toBuffer()));
  const bytes=await sharp(pngs,{join:{animated:true}}).gif({delay:Array(12).fill(100),loop:0}).toBuffer();
  await page.getByLabel("Challenge image").setInputFiles({name:"scene.gif",mimeType:"image/gif",buffer:bytes});
  await expect(page.getByRole("button",{name:"Use these frames",exact:true})).toBeVisible();
  await page.getByText("Adjust frames",{exact:true}).click();
  await page.getByLabel("Browse moments").fill("2");
  await page.getByRole("button",{name:"Replace selected frame",exact:true}).click();
  await page.getByRole("button",{name:"Use these frames",exact:true}).click();
  await expect(page.getByRole("button",{name:"Frames confirmed",exact:true})).toBeVisible();
  await page.getByText("Review image understanding",{exact:true}).click();
  await expect(page.getByLabel("Image description",{exact:true})).toHaveValue("A yellow square fills the image.");
  await page.getByLabel("I confirm this image description").check();
  await page.getByLabel("Your caption").fill("My week has twelve stages of denial.");
  await page.getByRole("button",{name:"Create draft",exact:true}).click();
  await expect(page).toHaveURL(/\/challenges\/[0-9a-f-]+$/);
  const id=page.url().split("/").pop()!;
  const {data: image,error}=await owner.client.from("challenge_images").select("*").single();
  expect(error).toBeNull();
  expect(image.media_format).toBe("gif");
  expect(image.selected_frames).toContain(2);
  expect(image.selected_frames).not.toContain(0);
  expect(image.prompt.frames).toEqual(image.selected_frames);
  expect(image.prompt.representation).toBe("gif-confirmed-frames-v1");
  const {data: stored}=await owner.client.storage.from("challenge-images").download(image.storage_path);
  expect((await sharp(Buffer.from(await stored!.arrayBuffer()),{animated:true}).metadata()).pages).toBe(12);
  expect((await voter.client.from("challenge_images").select("*")).data).toEqual([]);
  expect((await owner.client.from("challenge_images").update({selected_frames:[0]}).eq("id",image.id)).error).toBeTruthy();
  expect((await accounts.admin.from("challenge_images").update({selected_frames:[0]}).eq("id",image.id)).error).toBeTruthy();
  await page.getByRole("button",{name:"Generate AI opponent",exact:true}).click();
  await expect(page.getByRole("button",{name:"Publish for 24 hours",exact:true})).toBeVisible();
  const {data: generation}=await owner.client.from("challenge_generations").select("prompt").eq("challenge_id",id).single();
  expect(generation!.prompt.frames).toEqual(image.selected_frames);
  await page.getByRole("button",{name:"Publish for 24 hours",exact:true}).click();
  await expect(page.getByRole("main").getByRole("alert")).toContainText("awaiting moderator review");
  expect((await owner.client.rpc("publish_caption_challenge",{p_challenge:id})).error).toBeTruthy();
  expect((await owner.client.rpc("review_challenge_gif",{p_image:image.id,p_approved:true})).error).toBeTruthy();
  expect((await voter.client.rpc("list_unreviewed_gifs")).error).toBeTruthy();
  expect((await accounts.anonymous.rpc("review_challenge_gif",{p_image:image.id,p_approved:true})).error).toBeTruthy();
  expect((await accounts.admin.from("moderators").insert({user_id:moderator.id})).error).toBeNull();
  await page.getByText("Account",{exact:true}).click();
  await page.getByRole("button",{name:"Sign out"}).click();
  await expect(page).toHaveURL(/\/login$/);
  await login(page,moderator);
  await page.goto("/moderation");
  await expect(page.getByRole("img",{name:"Full GIF awaiting moderator review"})).toBeVisible();
  await expect(page.getByRole("button",{name:"Approve full GIF"})).toBeDisabled();
  await page.getByLabel("I reviewed the full animation, including transitions and brief text.").check();
  await page.getByRole("button",{name:"Approve full GIF"}).click();
  await expect(page.getByRole("button",{name:"Approve full GIF"})).toHaveCount(0);
  expect((await owner.client.rpc("publish_caption_challenge",{p_challenge:id})).error).toBeNull();
  expect((await voter.client.rpc("read_caption_challenge",{p_challenge:id})).data.captions).toHaveLength(2);
  expect((await voter.client.storage.from("challenge-images").createSignedUrl(image.storage_path,60)).error).toBeNull();
});
