import { test, expect, login, approveForTest } from "./fixtures";
import sharp from "sharp";

test("blocked text and unavailable checks leave an editable form and never create a publishable draft", async ({ page, accounts }) => {
  const owner = await accounts.create();
  await login(page, owner);
  await page.goto("/challenges/new");
  await page.getByLabel("Image source", { exact: true }).selectOption("template");
  const { data: images } = await owner.client.from("images").select("id").limit(1);
  await page.getByLabel("Gallery template", { exact: true }).selectOption(images![0].id);
  await page.getByText("Review image understanding", { exact: true }).click();
  await page.getByLabel("Image description", { exact: true }).fill("A surprised cartoon character.");
  await page.getByLabel("I confirm this image description").check();
  await page.getByLabel("Your caption").fill("[[test:block]]");
  await page.getByRole("button", { name: "Create draft", exact: true }).click();
  await expect(page.getByRole("main").getByRole("alert")).toContainText("targeted harassment");
  expect((await owner.client.from("challenges").select("id")).data).toEqual([]);
  await page.getByLabel("Your caption").fill("[[test:unavailable]]");
  await page.getByRole("button", { name: "Create draft", exact: true }).click();
  await expect(page.getByRole("main").getByRole("alert")).toContainText("Safety checking is unavailable");
  expect((await owner.client.from("challenges").select("id")).data).toEqual([]);
  await page.getByLabel("Your caption").fill("My optimism requested a leave of absence.");
  await page.getByRole("button", { name: "Create draft", exact: true }).click();
  await expect(page).toHaveURL(/\/challenges\/[0-9a-f-]+$/);
});

test("publication cannot bypass moderation, and hidden reports disappear from reads, votes, storage and winners", async ({ page, accounts }) => {
  const owner = await accounts.create();
  const voter = await accounts.create();
  const moderator = await accounts.create();
  const path = `${owner.id}/moderation.jpg`;
  const bytes = await sharp({ create: { width: 8, height: 8, channels: 3, background: "yellow" } }).jpeg().toBuffer();
  expect((await accounts.admin.storage.from("challenge-images").upload(path, bytes, { contentType: "image/jpeg" })).error).toBeNull();
  const { data: id, error } = await accounts.admin.rpc("create_caption_challenge", { p_owner: owner.id, p_image: path, p_template: null, p_situation: "Moderation fixture", p_caption: "Human fixture" });
  expect(error).toBeNull();
  const { data: request } = await accounts.admin.rpc("claim_caption_generation", { p_owner: owner.id, p_challenge: id, p_provider: "mock", p_model: "fixture", p_prompt: {} });
  expect((await accounts.admin.rpc("finish_caption_generation", { p_request: request, p_caption: "AI fixture" })).error).toBeNull();
  expect((await owner.client.rpc("publish_caption_challenge", { p_challenge: id })).error).toBeTruthy();
  expect((await owner.client.from("challenges").update({ human_moderation_id: request }).eq("id", id)).error).toBeTruthy();
  expect((await owner.client.from("moderation_checks").insert({ owner_id: owner.id, phase: "human", input_hash: "forged", policy_version: "moderation-v1", status: "approved", provider: "forged", model: "forged" })).error).toBeTruthy();
  await approveForTest(accounts.admin, owner.id, id);
  expect((await owner.client.rpc("publish_caption_challenge", { p_challenge: id })).error).toBeNull();
  const { data: challenge } = await voter.client.rpc("read_caption_challenge", { p_challenge: id });
  expect((await voter.client.rpc("vote_caption_challenge", { p_challenge: id, p_caption: challenge.captions[0].id })).error).toBeNull();
  expect((await accounts.admin.from("challenges").update({ closes_at: "2000-01-01T00:00:00Z" }).eq("id", id)).error).toBeNull();
  expect((await voter.client.rpc("list_challenge_winners")).data.some((w: { challenge_id: string }) => w.challenge_id === id)).toBe(true);
  expect((await voter.client.storage.from("challenge-images").createSignedUrl(path, 60)).error).toBeNull();
  expect((await voter.client.rpc("hide_challenge", { p_challenge: id })).error).toBeTruthy();
  expect((await voter.client.from("moderators").insert({ user_id: voter.id })).error).toBeTruthy();
  expect((await voter.client.rpc("list_challenge_reports")).error).toBeTruthy();
  expect((await accounts.anonymous.rpc("report_challenge", { p_challenge: id, p_reason: "hate" })).error).toBeTruthy();
  await login(page, voter);
  await page.goto(`/challenges/${id}`);
  await page.getByText("Report this challenge", { exact: true }).click();
  await page.getByRole("button", { name: "Submit report" }).click();
  await expect(page.getByText("Report received. Thank you.")).toBeVisible();
  expect((await voter.client.rpc("report_challenge", { p_challenge: id, p_reason: "other" })).error).toBeNull();
  expect((await voter.client.from("challenge_reports").select("id")).data).toHaveLength(1);
  expect((await owner.client.from("challenge_reports").select("id")).data).toEqual([]);
  expect((await accounts.admin.from("moderators").insert({ user_id: moderator.id })).error).toBeNull();
  await page.getByText("Account", { exact: true }).click();
  await page.getByRole("button", { name: "Sign out" }).click();
  await expect(page).toHaveURL(/\/login$/);
  await login(page, moderator);
  await page.goto("/moderation");
  await expect(page.getByText("Moderation fixture", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Hide challenge", exact: true }).click();
  await expect(page.getByText("No open reports.")).toBeVisible();
  expect((await voter.client.rpc("read_caption_challenge", { p_challenge: id })).data).toBeNull();
  expect((await voter.client.from("challenges").select("id").eq("id", id)).data).toEqual([]);
  expect((await voter.client.rpc("list_challenge_winners")).data.some((w: { challenge_id: string }) => w.challenge_id === id)).toBe(false);
  expect((await voter.client.storage.from("challenge-images").createSignedUrl(path, 60)).error).toBeTruthy();
  expect((await voter.client.rpc("vote_caption_challenge", { p_challenge: id, p_caption: null })).error).toBeTruthy();
  expect((await owner.client.rpc("publish_caption_challenge", { p_challenge: id })).error).toBeTruthy();
  expect((await owner.client.rpc("read_caption_challenge", { p_challenge: id })).data.hidden_at).toBeTruthy();
});

test("template visual review is moderator-only and can be completed from the queue", async ({ page, accounts }) => {
  const owner = await accounts.create();
  const { data: images } = await owner.client.from("images").select("id").limit(1);
  const id = images![0].id;
  expect((await accounts.admin.from("challenge_template_reviews").delete().eq("template_id", id)).error).toBeNull();
  expect((await owner.client.rpc("approve_challenge_template", { p_template: id })).error).toBeTruthy();
  await login(page, owner);
  await page.goto("/challenges/new");
  await page.getByLabel("Image source", { exact: true }).selectOption("template");
  await page.getByLabel("Gallery template", { exact: true }).selectOption(id);
  await page.getByText("Review image understanding", { exact: true }).click();
  await page.getByLabel("Image description", { exact: true }).fill("A scene.");
  await page.getByLabel("I confirm this image description").check();
  await page.getByLabel("Your caption").fill("A caption.");
  await page.getByRole("button", { name: "Create draft", exact: true }).click();
  await expect(page.getByRole("main").getByRole("alert")).toContainText("visual review");
  expect((await accounts.admin.from("moderators").insert({ user_id: owner.id })).error).toBeNull();
  await page.goto("/moderation");
  await page.getByRole("button", { name: "Approve template for challenges" }).click();
  await expect(page.getByRole("button", { name: "Approve template for challenges" })).toHaveCount(0);
  expect((await accounts.admin.from("challenge_template_reviews").select("template_id").eq("template_id", id).single()).data?.template_id).toBe(id);
});

test("AI output is checked again at publication even for an existing ready draft", async ({ page, accounts }) => {
  const owner = await accounts.create();
  const { data: images } = await owner.client.from("images").select("id").limit(1);
  const { data: id } = await accounts.admin.rpc("create_caption_challenge", { p_owner: owner.id, p_image: null, p_template: images![0].id, p_situation: "A scene", p_caption: "A human line" });
  const { data: request } = await accounts.admin.rpc("claim_caption_generation", { p_owner: owner.id, p_challenge: id, p_provider: "mock", p_model: "fixture", p_prompt: {} });
  expect((await accounts.admin.rpc("finish_caption_generation", { p_request: request, p_caption: "[[test:block]]" })).error).toBeNull();
  await login(page, owner);
  await page.goto(`/challenges/${id}`);
  await page.getByRole("button", { name: "Publish for 24 hours" }).click();
  await expect(page.getByRole("main").getByRole("alert")).toContainText("targeted harassment");
  expect((await owner.client.from("challenges").select("status").eq("id", id).single()).data?.status).toBe("ready");
  expect((await owner.client.rpc("publish_caption_challenge", { p_challenge: id })).error).toBeTruthy();
});

test("moderators can dismiss reports and creators can withdraw their own published challenge", async ({ page, accounts }) => {
  const owner = await accounts.create();
  const reporter = await accounts.create();
  const moderator = await accounts.create();
  const { data: images } = await accounts.admin.from("images").select("id,image_url").limit(1);
  const { data: challenge, error } = await accounts.admin.from("challenges").insert({ creator_id: owner.id, template_id: images![0].id, template_url: images![0].image_url, situation: "Owner withdrawal fixture", status: "published", closes_at: new Date(Date.now() + 86400000).toISOString() }).select("id").single();
  expect(error).toBeNull();
  const id = challenge!.id;
  expect((await reporter.client.rpc("report_challenge", { p_challenge: id, p_reason: "other" })).error).toBeNull();
  const { data: report } = await reporter.client.from("challenge_reports").select("id").single();
  expect((await reporter.client.rpc("dismiss_challenge_report", { p_report: report!.id })).error).toBeTruthy();
  expect((await accounts.admin.from("moderators").insert({ user_id: moderator.id })).error).toBeNull();
  await login(page, moderator);
  await page.goto("/moderation");
  await page.getByRole("button", { name: "Dismiss report" }).click();
  await expect(page.getByText("No open reports.")).toBeVisible();
  expect((await reporter.client.rpc("read_caption_challenge", { p_challenge: id })).data).not.toBeNull();
  await page.getByText("Account", { exact: true }).click();
  await page.getByRole("button", { name: "Sign out" }).click();
  await expect(page).toHaveURL(/\/login$/);
  await login(page, owner);
  await page.goto(`/challenges/${id}`);
  await page.getByText("Manage visibility", { exact: true }).click();
  await page.getByRole("button", { name: "Hide challenge", exact: true }).click();
  await expect(page.getByText("This challenge is hidden from other members. Voting and publication are disabled.")).toBeVisible();
  expect((await reporter.client.rpc("read_caption_challenge", { p_challenge: id })).data).toBeNull();
});

test("moderation claims are exclusive, cached, bounded and count old retries against today's quota", async ({ accounts }) => {
  const owner = await accounts.create();
  const args = { p_owner: owner.id, p_phase: "human", p_hash: "exclusive", p_policy: "moderation-v1", p_provider: "mock", p_model: "fixture" };
  expect((await owner.client.rpc("claim_moderation", args)).error).toBeTruthy();
  const claims = await Promise.all([accounts.admin.rpc("claim_moderation", args), accounts.admin.rpc("claim_moderation", args)]);
  expect(claims.filter(c => c.data?.claimed)).toHaveLength(1);
  const claimed = claims.find(c => c.data?.claimed)!.data;
  expect((await accounts.admin.from("moderation_checks").update({ status: "approved" }).eq("id", claimed.id)).error).toBeNull();
  const cached = await accounts.admin.rpc("claim_moderation", args);
  expect(cached.data).toMatchObject({ id: claimed.id, status: "approved", attempts: 1, claimed: false });
  const { data: old } = await accounts.admin.from("moderation_checks").insert({ owner_id: owner.id, phase: "human", input_hash: "old", policy_version: "moderation-v1", provider: "mock", model: "fixture", status: "error", attempts: 2, created_at: "2000-01-01T00:00:00Z", started_at: "2000-01-01T00:00:00Z" }).select("id").single();
  const retry = await accounts.admin.rpc("claim_moderation", { ...args, p_hash: "old" });
  expect(retry.error).toBeNull();
  expect(retry.data.attempts).toBe(3);
  expect((await accounts.admin.from("moderation_checks").update({ status: "error" }).eq("id", old!.id)).error).toBeNull();
  expect((await accounts.admin.rpc("claim_moderation", { ...args, p_hash: "old" })).error).toBeTruthy();
  const remaining = await Promise.all(Array.from({ length: 40 }, (_, i) => accounts.admin.rpc("claim_moderation", { ...args, p_hash: `quota-${i}` })));
  expect(remaining.filter(r => !r.error)).toHaveLength(36);
});
