-- ARCHIVED ENTRY POINT: do not execute.
-- Canonical source: ../migrations/202610020004_finish_profile_cutover.sql
-- Hosted cutover is already complete and recorded. Kept as a pointer for old links.
